#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
    echo "${PREREQ}"
}

case "${1}" in
    prereqs)
	prereqs
	exit 0
	;;
esac

# live-initramfs header

. /scripts/live-functions

# live-initramfs script

# bind the vyatta config directory with the following precedence
#	1) backing store if present
#	3) create live/"cow" which may or maynot be on a non-volatile device
#	   but is certainly read-write

if [ -d /root/opt/vyatta/etc/config ]
then
    if [ -d /root/live/cow/cow ]
    then
        if [ -d /root/live/cow/cow/config ]
        then
            log_begin_msg "Using /live/cow/cow/config..."
            mount -o bind /root/live/cow/cow/config /root/opt/vyatta/etc/config
            log_end_msg
        else
            log_begin_msg "Creating /live/cow/cow/config..."
            cp -a /root/opt/vyatta/etc/config /root/live/cow/cow
            mount -o bind /root/live/cow/cow/config /root/opt/vyatta/etc/config
            log_end_msg
        fi
    else
        if [ -d /root/live/cow/config ]
        then
	    log_begin_msg "Using /live/cow/config..."
	    mount -o bind /root/live/cow/config /root/opt/vyatta/etc/config
	    log_end_msg
        else
	    log_begin_msg "Creating /live/cow/config..."
	    cp -a /root/opt/vyatta/etc/config /root/live/cow
	    mount -o bind /root/live/cow/config /root/opt/vyatta/etc/config
	    log_end_msg
        fi
    fi
fi

# Local Variables:
# mode: shell-script
# sh-indentation: 4
# End:
