#!/bin/bash

cat > chroot/etc/live.conf <<EOF
USERNAME=vyatta
USERFULLNAME=Vyatta_live
HOSTNAME=vyatta
BUILD_SYSTEM=Debian
QUICKREBOOT=yes
export USERNAME USERFULLNAME HOSTNAME BUILD_SYSTEM QUICKREBOOT
EOF

sed -i 's/cat > \$FSTAB <<EOF/cat >>\$FSTAB <<EOF/' $livedir/12fstab

