#!/bin/bash

cat > chroot/etc/live.conf <<EOF
HOSTNAME=vyatta
BUILD_SYSTEM=Ubuntu
QUICKREBOOT=yes
export HOSTNAME BUILD_SYSTEM QUICKREBOOT
EOF

# patch live-initramfs scripts
( cd chroot/ && \
    for patch in ../patches/gutsy-*.patch ; do \
	patch -p1 < $patch ; \
    done )

