#!/bin/bash

cat > chroot/etc/live.conf <<EOF
HOSTNAME=vyatta
BUILD_SYSTEM=Ubuntu
QUICKREBOOT=yes
export HOSTNAME BUILD_SYSTEM QUICKREBOOT
EOF

# patch live-initramfs scripts
( cd chroot/ && \
    patch -p1 < ../patches/lenny-live-0.patch && \
    patch -p1 < ../patches/gutsy-umountfs-0.patch )

