#!/bin/bash

cat > chroot/etc/live.conf <<EOF
USERNAME=vyatta
USERFULLNAME=Vyatta_live
HOSTNAME=vyatta
BUILD_SYSTEM=Debian
QUICKREBOOT=yes
export USERNAME USERFULLNAME HOSTNAME BUILD_SYSTEM QUICKREBOOT
EOF

# patch live-initramfs scripts
( cd chroot/ && patch -p1 < ../patches/lenny-live-0.patch )

