#!/bin/bash

cat > chroot/etc/live.conf <<EOF
USERNAME=vyatta
USERFULLNAME=Vyatta_live
HOSTNAME=vyatta
BUILD_SYSTEM=Debian
QUICKREBOOT=yes
export USERNAME USERFULLNAME HOSTNAME BUILD_SYSTEM QUICKREBOOT
EOF

( cd chroot/ && \
    for patch in ../patches/lenny-*.patch ; do \
	patch -p1 < $patch ; \
    done )

