#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
    echo "${PREREQ}"
}

case "${1}" in
    prereqs)
	prereqs
	exit 0
	;;
esac

# live-initramfs header

. /scripts/live-functions

failure()
{
    log_failure_msg "$*"
    exit 1
}

# live-initramfs script

# these hacks address deficiencies of the livecd "exposedroot" feature
# namely, /etc and /media need to be writable

if grep -q ' exposedroot' /proc/cmdline
then
    log_begin_msg "Vyatta exposed root..."
    if grep -q aufs /proc/filesystems
    then
	UNIONTYPE=aufs
    else
	UNIONTYPE=unionfs
    fi
    mkdir -p /root/live/etc
    [ -d /root/live/etc ] || \
	failure "Can't create /root/live/etc"
    mount -t $UNIONTYPE \
	-o rw,noatime,dirs=/root/live/etc=rw:/root/etc=ro \
	$UNIONTYPE /root/etc || \
	failure "Can't union /root/live/etc with /root/etc"
    mount -t tmpfs tmpfs /root/media || \
	failure "Can't mount tmpfs for /root/media"
    log_end_msg
fi

# Local Variables:
# mode: shell-script
# sh-indentation: 4
# End:
