#!/bin/bash -e

# for convert_system_path_to_grub_path()
source /usr/lib/grub/update-grub_lib

# check for usable backgrounds
background=/boot/graphics/vyatta_lower_right_640x480.tga
graphic_module=${background##*.}
if [[ -z "$GRUB_TERMINAL" || "$GRUB_TERMINAL" = "gfxterm" ]] && \
    [ -e "$background" ] ; then
    cat <<-EOF
	insmod $graphic_module
	if background_image $background ; then
	    set color_normal=light-gray/black
	    set color_highlight=magenta/black
	    set menu_color_normal=light-gray/black
	    set menu_color_highlight=white/black
	fi
	EOF
fi

# Local Variables:
# mode: shell-script
# sh-indentation: 4
# End:
