#!/bin/bash

shopt -s nullglob

echo I: Remove initramfs console, thermal, and splash hooks
rm -f usr/share/initramfs-tools/hooks/{console_*,thermal,usplash}
rm -f usr/share/initramfs-tools/scripts/init-top/{framebuffer,console_setup}

echo I: Remove hwclock and non-serial console init
rm -f etc/rc?.d/[SK]*{hwclock*,keyboard-setup,console-*}

echo I: Remove hwclock udev rule
rm -f etc/udev/rules.d/85-hwclock.rules

# echo I: Enable Verbose init
# sed -i 's/^\(VERBOSE\)=no/\1=yes/' etc/default/rcS

