#!/bin/sh

shopt -s nullglob

echo I: Disable video console
cat <<EOF > etc/default/console-setup
ACTIVE_CONSOLES=''
EOF

echo I: Remove initramfs thermal hook
rm -f usr/share/initramfs-tools/hooks/thermal

echo I: Remove hwclock
rm -f etc/rc?.d/[SK]*hwclock*

echo I: Remove hwclock udev rule
rm -f etc/udev/rules.d/85-hwclock.rules

# echo I: Enable Verbose init
# sed -i 's/^\(VERBOSE\)=no/\1=yes/' etc/default/rcS

