#!/bin/bash

echo I: Remove initramfs console, thermal, and splash hooks
rm -f usr/share/initramfs-tools/hooks/console_setup 
rm -f usr/share/initramfs-tools/hooks/console_tools 
rm -f usr/share/initramfs-tools/hooks/thermal 
rm -f usr/share/initramfs-tools/hooks/usplash
rm -f usr/share/initramfs-tools/scripts/init-top/framebuffer 
rm -f usr/share/initramfs-tools/scripts/init-top/console_setup 

echo I: Remove hwclock and non-serial console init
rm -f etc/rc?.d/[SK]*hwclock*
rm -f etc/rc?.d/[SK]*keyboard-setup
rm -f etc/rc?.d/[SK]*console-setup
rm -f etc/rc?.d/[SK]*console-screen.sh

# echo I: Enable Verbose init
# sed -i 's/^\(VERBOSE\)=no/\1=yes/' etc/default/rcS

