#!/bin/sh
#
# This scripts starts from a virgin debian install;
# it adds all packages needed to build a Vyatta .iso;
# it then "git clone"s the remote repositories
# and actually builds the .iso .
# It requires root priveleges
#
# For further information, see the vyatta community wiki:
# http://www.vyatta.com/twiki/bin/view/Community/WebHome
#
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# Author: Rick Balocca
# Date: 2007
# Description:
# 
# **** End License ****

case "$1" in
 -f )
	full_path=yes
	shift
	;;
esac

path_to()
{
	local mypath

	mypath="$1"
	chmod +x "$mypath" 2>/dev/null
	if which "$mypath"  >/dev/null
	then
		# path is OK
		return 0
	fi

	chmod +x "$0" 2>/dev/null
	mypath=`which $0`
	mypath=`dirname "$mypath"`/"$1"
	chmod +x "$mypath" 2>/dev/null
	if which "$mypath"  >/dev/null
	then
		PATH="$PATH":`dirname "$mypath"`
		return 0
	fi

	echo Cannot find "$1"
	exit 1
}

path_to latestdeb

list=`find $* -type f -name '*.deb' -exec basename {} \;|sed 's/_.*$//'|sort -u`
for i in $list
do
	nm=`latestdeb $i`
	if [ "$full_path" ]
	then
		echo $nm
	else
		prefix=`basename "$nm" | sed -e 's/_.*$//'`
		echo -n "$prefix"" "
		dpkg -f "$nm" version | sed 's/[0-9]://'
	fi
done | sort -u 
