#!/bin/sh
#
# This scripts starts from a virgin debian install;
# it adds all packages needed to build a OFR .iso;
# it then "git-clone"s the remote repositories
# and actually builds the .iso .
# It requires root priveleges
#
# For further information, see the vyatta community wiki:
# http://www.vyatta.com/twiki/bin/view/Community/WebHome
#
# **** License ****
# Version: VPL 1.0
# 
# The contents of this file are subject to the Vyatta Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.vyatta.com/vpl
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2007 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Rick Balocca
# Date: 2007
# Description:
# 
# **** End License ****

case "$1" in
 -f )
	full_path=yes
	shift
	;;
esac

list=`find $* -type f -name '*.deb' -exec basename {} \;|sed 's/_.*$//'|sort -u`
for i in $list
do
	nm=`latestdeb $i`
	if [ "$full_path" ]
	then
		echo $nm
	else
		prefix=`basename "$nm" | sed -e 's/_.*$//'`
		echo -n "$prefix"" "
		dpkg -f "$nm" version | sed 's/[0-9]://'
	fi
done | sort -u 
