#!/usr/bin/perl -W

print "This script will run a git status on all the submodules in 'pkgs'.\n";
print "This script expects to be run from the root of the build where 'pkgs' is a subdir.\n";

if (! -d 'pkgs') {
	die "The subdirectory 'pkgs' has not been found in the current directory.  Are you sure you're in the root of the build?\n";
}

opendir PKGS, 'pkgs' or die "Problem getting 'pkgs' directory listing.";
my @pkgs = readdir PKGS;
closedir PKGS;

foreach $pkg (@pkgs) {

	if ($pkg ne '.' && $pkg ne '..' && -d "pkgs/$pkg/.git") {
		print "-- $pkg --\n";
		system "cd pkgs/$pkg; git status";
		print "\n";
	}
}
