#!/usr/bin/perl -W
#
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# **** End License ****


print "This script will run a git status on all the submodules in 'pkgs'.\n";
print "This script expects to be run from the root of the build where 'pkgs' is a subdir.\n";

if (! -d 'pkgs') {
	die "The subdirectory 'pkgs' has not been found in the current directory.  Are you sure you're in the root of the build?\n";
}

opendir PKGS, 'pkgs' or die "Problem getting 'pkgs' directory listing.";
my @pkgs = readdir PKGS;
closedir PKGS;

foreach $pkg (@pkgs) {

	if ($pkg ne '.' && $pkg ne '..' && -d "pkgs/$pkg/.git") {
		print "-- $pkg --\n";
		system "cd pkgs/$pkg; git status";
		print "\n";
	}
}
