#!/bin/bash
#
# **** License ****
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# **** End License ****


usage () {
  echo "usage: $0 <template_dir>"
  exit 1
}

tmpl_dir=$1
if [ -z "$tmpl_dir" ] || [ ! -d "$tmpl_dir" ]; then
  usage
fi

sep=$(dd if=/dev/urandom bs=4 count=4 2>/dev/null | base64)
find $tmpl_dir -name node.def \
  | while read tfile; do
      [ -f "$tfile" ] || continue
      while grep -q "^$sep\$" $tfile; do
        sep=$(dd if=/dev/urandom bs=4 count=4 2>/dev/null | base64)
      done
      echo -e "$tfile\n$sep"
      cat $tfile
      echo -e "\n$sep"
    done

