#!/bin/sh
#
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# **** End License ****


targetdir="$1"
shift

# Set defaults
[ "$targetdir" ] || targetdir=ofr
[ "$VYATTA_URL" ] || export VYATTA_URL=http://git.vyatta.com
repo=build-iso
bname=master

case "$targetdir" in
 ofr )
	repo=ofr
	;;
 alameda | bakersfield | camarillo | dublin | fairfield )
	repo=ofr
	bname="$targetdir"
	;;
 eureka | build-eureka | build-iso )
	;;
 * )	# post dublin
	bname="$targetdir"
	;;
esac

# Check for differently named targetdir
if [ "$1" = -targetdir -a "$2" ]
then
	shift
	targetdir="$1"
	shift
fi

if [ -d "$targetdir" ]
then
	echo Sorry, target directory "$targetdir" already exists
	exit 1
fi

git clone -q "$VYATTA_URL/$repo".git "$targetdir"

cd "$targetdir"

if [ "$bname" != master ]
then
	git checkout -b "$bname" "remotes/origin/$bname"
	git config "branch.$bname.remote" origin
	git config "branch.$bname.merge" "refs/heads/$bname"
fi

autoreconf -i && ./configure $*>/dev/null
