#!/bin/sh
#
# This script reports the debian packages in the pool
# For packages with more than one version, it only lists
# the file with the highest version number
#
# For further information, see the vyatta community wiki:
# http://www.vyatta.com/twiki/bin/view/Community/WebHome
#
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# Author: Rick Balocca
# Date: 2007
# Description:
# 
# **** End License ****

get_dpkg_version()
{
	if [ "$1" ]
	then
		dpkg-deb --field "$1" version
	else
		echo 0
	fi
}

newer_package()
{
	local new_no
	local old_no

	new_no=0
	old_no=0
	[ "$1" ] && new_no=`get_dpkg_version "$1"`
	[ "$2" ] && old_no=`get_dpkg_version "$2"`

	if dpkg --compare-versions "$new_no" ">" "$old_no"
	then
		echo "$1"
	else
		echo "$2"
	fi
}

accumulate_newest()
{
	local newest

	newest=
	for i in $*
	do
		newest=`newer_package "$newest" "$i"`
	done
	echo $newest
}

latestdeb()
{
	archive_prefix=`echo "$1" | sed 's/_.*//'`
	archive=`basename "$archive_prefix"`
	dir=`dirname "$1"`
	list=`find "$dir" -type f -name "$archive"_"*.deb"`
	accumulate_newest $list
}

latestdeb "$1"
