#!/bin/sh

POOL_DIR=/var/www/vyatta/pool/$1/main
mkdir -p ${POOL_DIR}

shift
for pkg in $@; do
  echo uploading $pkg...
  case "$pkg" in
    kernel )
      deb="kernel/linux-*.deb"
      ;;
    * )
      deb="${pkg}/${pkg}*.deb"
      ;; 
  esac
  cp ${deb} ${POOL_DIR}/
done
