#!/bin/sh
#
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# **** End License ****

POOL_DIR=/var/www/vyatta/pool/$1/main
mkdir -p ${POOL_DIR}

shift
for pkg in $@; do
  echo uploading $pkg...
  case "$pkg" in
    kernel )
      deb="kernel/linux-*.deb"
      ;;
    * )
      deb="${pkg}/${pkg}*.deb"
      ;; 
  esac
  cp ${deb} ${POOL_DIR}/
done
