#!/bin/bash
#
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# **** End License ****

# this script shows the unreleased changes in submodules.

show_all=no
while getopts a opt
do
  case "$opt" in
    a )
      # show all unreleased changes
      show_all=yes
      ;;
  esac
done

(
  cd pkgs
  for r in */.git; do
    (
      cd ${r%%/.git}
      tag=$(git describe --tags --abbrev=0 --match 'debian/*')
      if ! git diff --quiet HEAD $tag; then
        echo "====== Unreleased change(s) in ${r%%/.git} ======"
        if [ "$show_all" == yes ]; then
          git log --no-merges HEAD ^$tag
        else
          git log --no-merges --max-count=1
        fi
        echo
      fi
    )
  done
)

