#!/bin/bash
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# **** End License ****

progname=${0##*/}
shopt -s nullglob
cd pkgs

info=echo
trace=
git_clean_flag=-f
do_debclean=false
do_gitclean=false
do_wipe=false

declare -a cloned=( */debian )
declare -a submodule=( ${cloned[@]%/*} )
declare -a targets

while [ $# -gt 0 ] ; do
    case "$1" in
	-h | --help )
	    cat <<-EOF
Usage: $progname [-n] [ SUBMODULE... ]
Option:
  -n | --do-nothing     Don´t actually remove anything,
                        just show what would be done.
  -q | --quiet          Quiet, don't print progress info
  -d | --debclean       Also clean debian build stage
  -g | --gitclean       Also clean git tree
  -w | --wipe           Remove submodule tree and repos

If no SUBMODULE(s) given, clean all checked-out submodules
EOF
	    exit 0;;
	-n | --do-nothing )
	    trace=echo
	    git_clean_flag=-n
	    shift;;
	-q | --quiet )
	    info='#'
	    shift;;
	-d | --debclean )
	    do_debclean=true
	    shift;;
	-g | --gitclean )
	    do_gitclean=true
	    shift;;
	-w | --wipe )
	    do_wipe=true
	    shift;;
	-* )
	    echo Unkown option: \""$1"\"
	    exit 1;;
	* )
	    submodule=( $@ )
	    break;;
    esac
done

for (( i=0; i<${#submodule[@]}; i++)) ; do
    eval $info P: ${submodule[i]}    
    case "${submodule[i]}" in
	linux-* )
	    targets=( linux-*.{build,changes,deb,tar.gz,udeb} );;
	vyatta-dhcp3-client )
	    targets=( vyatta-dhcp3*.{build,changes,deb,tar.gz,udeb} );;
	vyatta-snort )
	    targets=( vyatta-snort*.{build,changes,deb,tar.gz,udeb} );;
	vyatta-grub )
	    targets=( grub*.{build,changes,deb,tar.gz,udeb} );;
	iproute | iptables | open-vm-tools )
	    targets=( ${submodule[i]}*.{build,changes,deb,tar.gz,udeb} );;
	net-snmp )
	    targets=( *snmp*.{build,changes,deb,tar.gz,udeb} tkmib*.deb );;
	ppp )
	    targets=( vyatta-ppp*.{build,changes,deb,tar.gz,udeb} );;
	* )
	    targets=( ${submodule[i]}_*.{build,changes,deb,tar.gz,udeb} );;
    esac
    if eval $do_wipe ; then
	targets+=( ${submodule[i]}/* ${submodule[i]}/.[^.]* )
    else
	eval $do_debclean && \
	    ( cd ${submodule[i]} ; eval $trace debclean )
	eval $do_gitclean && \
	    ( cd ${submodule[i]} ; git clean $git_clean_flag -d )
    fi
    if [[ ${#targets[@]} -gt 0 ]] ; then
	eval $trace rm -rf ${targets[@]} ${submodule[i]}/debian/files
    fi
done
