#!/bin/bash

progname=${0##*/}
shopt -s nullglob
cd pkgs 2>/dev/null

info=echo
trace=
git="git_status"

declare -a cloned=( */.git pkgs/*/.git )
declare -a submodule=( ${cloned[@]%/*} )

while [ $# -gt 0 ] ; do
    case "$1" in
	-h | --help )
	    cat <<-EOF
Usage: $progname [-n | -q] COMMAND [ SUBMODULE... ]
Option:
  -n		Don´t actually execute anything,
		just show what would be done.
  -q		Quiet, don't print progress info

COMMAND:
  branch	Show current branch
  branch-av	Show all branches
  clean		Clean tree of non-indexed files
  clean-n	Show files to be cleaned
  diff		Show diff from HEAD to tree
  diff-cached	Show diff from HEAD to index cache
  fetch		Fetch updates
  lsmods	ls-files -m
  merge		merge current branch with origin/BRANCH
  pull		fetch and merge current branch 
  push		push commits upstream
  status	Show status (default)
  update-mods	Update index for all modified files

SUBMODULE:
  If no submodule given, perform git-COMMAND on all checked-out submodules

EOF
	    exit 0;;
	-n )
	    trace=echo
	    shift;;	    
	-q )
	    info='#'
	    shift;;
	  branch \
	      | branch-av \
	      | clean \
	      | clean-n \
	      | diff \
	      | diff-cached \
	      | fetch \
	      | lsmods \
	      | merge \
	      | pull \
	      | push \
	      | status \
	      | checkout \
	      | push-with-tags \
	      | update-mods )
	      git=git_$1
	      shift;;
	* )
	    submodule=( $@ )
	    break;;
    esac
done

git_pull ()
{
    git-pull
}

git_push ()
{
    git-push
}

git_push-with-tags ()
{
    git-push --tags
}

git_diff ()
{
    git-diff
}

git_branch ()
{
    git-branch
}

git_branch-av ()
{
    git-branch -a -v
}

git_clean-n ()
{
    git-clean -n
}

git_lsmods ()
{
    git-ls-files -m
}

get_branch_info()
{
    git-branch|grep '^\* '|sed 's/(no branch)/NOBRANCH/'
}

get_branch()
{
    get_branch_info|awk '{ print $2 }'
}

guess_branch()
{
    local branch

    branch=`get_branch`
    [ "$branch" = NOBRANCH -o ! "$branch" ] && branch="$SUPERBRANCH"
    [ "$branch" = NOBRANCH ] && branch=master
    echo "$branch"
}

get_sha()
{
    get_branch_info|awk '{ print $3 }'
}

git_checkout()
{
	if ! git-checkout "$SUPERBRANCH" 2>/dev/null
	then
		echo No branch "$branch"
	fi
}

git_fetch ()
{
    local modulename=`basename "$PWD"`

    git-fetch -q 2>/dev/null
    if git-status|grep '^# Changes to be committed:' >/dev/null
    then
	echo There are uncommited changes.
    fi

    if git-status|grep '^# Changed but not updated:' >/dev/null
    then
	echo There are changes not yet added.
    fi

    if (git-status|grep '^# Untracked files:' >/dev/null) ; then
	echo There are untracked files.
    fi

    (
    if cd ../../.git 2>/dev/null
    then
	parent=`cd .. && git-submodule status pkgs/"$modulename"|sed 's/\(.\).*/\1/'`;
	case "$parent" in
	    '+' ) echo This submodule has a commit not in the parent.;;
	    '-' ) echo This submodule is not up to date.;;
	esac
    fi
    )

    branch=`guess_branch`
    upstream=origin/"$branch"
    git-cat-file -e "$upstream" || upstream=origin/master

    diffs=`git-diff "$upstream"|head -1`
    in_repo_local=
    in_repo=
    if [ "$diffs" ]
    then 
	in_repo_local=`git-log -1 --name-status "$upstream".."$branch" 2>/dev/null`
	[ "$in_repo_local" ] && echo A local commit is not in the shared repo.

	in_repo=`git-log -1 --name-status "$branch".."$upstream" 2>/dev/null`
	[ "$in_repo" ] && echo Local branch does not have a commit from the shared repo.
   fi

   git-branch -a -v|sed 's/..//'|grep -v '^origin/'|awk '{print $2}'|sort -u>/tmp/$$-branchlist
   git-branch -a -v|sed 's/..//'|grep    '^origin/'|awk '{print $2}'|sort -u>/tmp/$$-originlist
   local_only=`comm -23 /tmp/$$-{branchlist,originlist}`
   rm -rf /tmp/$$-{branchlist,originlist}
   [ "$local_only" -a ! "$in_repo_local" -a ! "$in_repo" ] && echo "The shared repo is missing a commit from a non-checked-out local branch (or no branch is checked out at all)."
}

git_diff-cached ()
{
    git-diff --cached
}

git_update-mods ()
{
    git-ls-files -m | git-update-index --stdin
}

git_status()
{
	git-status|grep -v -e '^nothing to commit' -e '^# On branch '
}

SUPERBRANCH=`get_branch`
eval $info ========= . =========
eval $trace $git
for (( i=0; i<${#submodule[@]}; i++)) ; do
    eval $info ========= pkgs/${submodule[i]} =========
    ( cd ${submodule[i]} ; eval $trace $git )
done
