#!/bin/bash

progname=${0##*/}
shopt -s nullglob
cd pkgs

trace=

declare -a cloned=( */debian )
declare -a submodule=( ${cloned[@]%/*} )

while [ $# -gt 0 ] ; do
    case "$1" in
	-h | --help )
	    cat <<-EOF
Usage: $progname [-n] [ SUBMODULE... ]
Option:
  -n	Don´t actually remove anything,
	just show what would be done.

If no SUBMODULE(s) given, clean all checked-out submodules
EOF
	    exit 0;;
	-n )
	    trace=echo
	    shift;;	    
	* )
	    submodule=( $@ )
	    break;;
    esac
done

for (( i=0; i<${#submodule[@]}; i++)) ; do
    case "${submodule[i]}" in
	linux-* )
	    eval $trace rm -f linux-*.{build,changes,deb,tar.gz,udeb} ;;
	vyatta-dhcp3-client )
	    eval $trace rm -f vyatta-dhcp3-*.{build,changes,deb,tar.gz,udeb} ;;
	wanpipe )
	    eval $trace rm -f wanpipe*.{build,changes,deb,tar.gz,udeb} ;;
	* )
	    eval $trace rm -f ${submodule[i]}_*.{build,changes,deb,tar.gz,udeb} ;;
    esac
    ( cd ${submodule[i]} ; eval $trace debclean )
done
