#!/bin/bash
#
# **** License ****
#
# Copyright (C) 2013 Vyatta, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# **** End License ****

usage () {
  echo "usage: $0 <input_file>"
  exit 1
}

infile=$1
if [ -z "$infile" ] || [ ! -f "$infile" ]; then
  usage
fi

outfile=''
sep=''
empty_line=''
IFS=""
cat $infile \
  | while read -r line; do
      if [ -z "$outfile" ]; then
        outfile=$line
        if [ -f "$outfile" ]; then
          >$outfile
        fi
      elif [ -z "$sep" ]; then
        sep=$line
      elif [ "$sep" == "$line" ]; then
        outfile=''
        sep=''
        empty_line=''
      elif [ -f "$outfile" ]; then
        if [ -n "$empty_line" ]; then
          echo >>$outfile
          empty_line=''
        fi
        if [ -z "$line" ]; then
          empty_line=yes
        else
          echo "$line" >>$outfile
        fi
      fi
    done

